services:
  frontend:
    build:
      context: ./src/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./src/frontend/
        target: /app
      - type: volume
        target: /app/cache/
      #   target: /app/node_modules
  backend:
    build:
      context: ./src/backend/
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    env_file:
      - ./src/db/.env
      - ./src/backend/.env
    ports:
      - 3001:3000
    volumes:
      - type: bind
        source: ./src/backend/
        target: /app
  db:
    image: postgres:13
    env_file:
      - ./src/db/.env
    volumes:
      - type: volume
        source: dbtest
        target: /app/db
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db:5432
    ports:
      - 3002:8080
  reverse-proxy:
    build:
      context: ./src/reverse-proxy
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - db
volumes:
  dbtest:
